# Generated by Django 6.0.2 on 2026-03-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('cpu', 'CPU'), ('gpu', 'GPU'), ('ram', 'RAM'), ('storage', 'Storage'), ('motherboard', 'Motherboard'), ('psu', 'PSU'), ('case', 'Case'), ('cooling', 'Cooling')], max_length=20)),
                ('sector', models.CharField(choices=[('Gaming', 'Gaming'), ('Students', 'Students'), ('IT', 'IT'), ('Creators', 'Creators')], max_length=20)),
                ('price', models.IntegerField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
