# Generated by Django 6.0.2 on 2026-03-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='description',
        ),
        migrations.AddField(
            model_name='component',
            name='power',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='component',
            name='ram_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='component',
            name='socket',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
