# Generated by Django 6.0.2 on 2026-03-04 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_remove_component_description_component_power_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.CharField(blank=True, max_length=200)),
                ('gpu', models.CharField(blank=True, max_length=200)),
                ('ram', models.CharField(blank=True, max_length=200)),
                ('motherboard', models.CharField(blank=True, max_length=200)),
                ('storage', models.CharField(blank=True, max_length=200)),
                ('psu', models.CharField(blank=True, max_length=200)),
                ('case', models.CharField(blank=True, max_length=200)),
                ('cooling', models.CharField(blank=True, max_length=200)),
                ('total_price', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
