# Generated by Django 6.0.2 on 2026-03-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='profit',
            field=models.IntegerField(default=0),
        ),
    ]
