# Generated by Django 6.0.2 on 2026-03-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='otp',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='profile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
