# Generated by Django 6.0.2 on 2026-03-06 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0007_component_image_profile_otp_profile_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='verified',
        ),
    ]
