# Generated by Django 6.0.2 on 2026-03-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0010_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_delivery',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
