# Generated by Django 6.0.2 on 2026-04-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0011_order_estimated_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='sector',
            field=models.CharField(choices=[('Gaming', 'Gaming'), ('Students', 'Students'), ('IT', 'IT'), ('Creators', 'Creators')], default='Gaming', max_length=20),
        ),
    ]
